version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: rightdoor
      POSTGRES_USER: rightdoor
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
